---FOR MOVIE TABLE------------------------------------------------------------------------------
SELECT NAME
FROM STARSIN, MOVIESTAR
WHERE STARNAME=NAME AND MOVIETITLE = 'The Usual Suspects' AND GENDER='M'

--Or you can use intersect 

--(SELECT NAME FROM MOVIESTAR where GENDER='M')
--intersect 
--(SELECT STARNAME from STARSIN where MOVIETITLE='The Usual Suspects')

SELECT STARNAME
FROM STARSIN,MOVIE
WHERE MOVIETITLE=TITLE AND YEAR=1995 AND STUDIONAME='MGM'

SELECT DISTINCT NAME
FROM MOVIE,MOVIEEXEC
WHERE STUDIONAME='MGM' AND PRODUCERC#=CERT# 

SELECT TITLE
FROM MOVIE
where LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars')

SELECT NAME
FROM MOVIEEXEC
where NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Stephen Spielberg')

SELECT TITLE
FROM MOVIE, (SELECT CERT#
FROM MOVIEEXEC
where NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Stephen Spielberg')) AS SUBQUERY
WHERE PRODUCERC#=CERT#

---FOR PC TABLE------------------------------------------------------------------------------

